# This is a basic workflow to help you get started with Actions

name: Docker Actions

# Controls when the action will run. 
on: [push, ]

env:
  GITTOKEN: "RandomText"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Show git info
        run: |
          echo "GITTOKEN: $GITTOKEN"

      # - name: hello-action
      #   uses: ./.github/actions/hello-world
      #   with:
      #     firstGreeting: ${{env.GITTOKEN}}
      
      # - name: meow
      #   uses: ./.github/actions/cat-facts
      #   id: cat
      #   with:
      #     firstGreeting: ${{env.GITTOKEN}}

      - name: docker meow
        run: |
          docker build -t PR_test .github/actions/cat-facts ./Dockerfile
        env:
          firstGreeting: ${{env.GITTOKEN}}
          GITTOKEN: ${{ inputs.firstGreeting }}

      # - name: create-issue
      #   uses: ./.github/actions/issue-maker
      #   with:
      #     repoToken: ${{secrets.GITHUB_TOKEN}}
      #     catFact: ${{steps.cat.outputs.fact}}
      #     issueTitle: "This issue was generated automatically"